v0.0.2

diff --git a/.github/workflows/deploy-docker.yml b/.github/workflows/deploy-docker.yml
--- a/.github/workflows/deploy-docker.yml
+++ b/.github/workflows/deploy-docker.yml
@@ -1,3 +1,57 @@
+# name: Publish Docker image
+
+# on:
+#   release:
+#     types: [published]
+
+# jobs:
+#   push_to_registry:
+#     name: Push Docker image to Docker Hub
+#     runs-on: ubuntu-latest
+#     permissions:
+#       packages: write
+#       contents: read
+#       attestations: write
+#     steps:
+#       - name: Check out the repo
+#         uses: actions/checkout@v4
+
+#       - name: Set up Go 1.x
+#         uses: actions/setup-go@v4
+#         with:
+#           go-version: 1.22.11
+#         id: go
+
+#       - name: Get dependencies
+#         run: |
+#           go mod download
+#           if [ -f Gopkg.toml ]; then
+#               curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
+#               dep ensure
+#           fi
+
+#       - name: Log in to Docker Hub
+#         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
+#         with:
+#           username: ${{ secrets.DOCKERHUB_USERNAME }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+#       - name: Extract metadata (tags, labels) for Docker
+#         id: meta
+#         uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
+#         with:
+#           images: terraharitri/elastic-indexer
+
+#       - name: Build and push Docker image
+#         id: push
+#         uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
+#         with:
+#           context: .
+#           file: ./Dockerfile
+#           push: true
+#           tags: ${{ steps.meta.outputs.tags }}
+#           labels: ${{ steps.meta.outputs.labels }}
+
 name: Publish Docker image
 
 on:
@@ -22,6 +76,22 @@ jobs:
           go-version: 1.22.11
         id: go
 
+      - name: Check Secret Availability
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "❌ DOCKERHUB_USERNAME is missing!"
+            exit 1
+          else
+            echo "✅ DOCKERHUB_USERNAME is set!"
+          fi
+
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "❌ DOCKERHUB_TOKEN is missing!"
+            exit 1
+          else
+            echo "✅ DOCKERHUB_TOKEN is set!"
+          fi
+
       - name: Get dependencies
         run: |
           go mod download
@@ -31,16 +101,17 @@ jobs:
           fi
 
       - name: Log in to Docker Hub
-        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
+        uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+          
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
         with:
-          images: terraharitri/elastic-indexer
+          images: terradharitri/elastic-indexer
 
       - name: Build and push Docker image
         id: push
@@ -51,4 +122,3 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-
